.TH automysqlbackup 8 "20 May 2014" "wipe_out" "Automatically backup MySQL"
.SH NAME
automysqlbackup \- backup all of your database daily, weekly, and monthly
.SH SYNOPSIS
 automysqlbackup
.br
.SH DESCRIPTION
 This manual page documents briefly the
.B automysqlbackup
command.
.PP
 configuration is stored within the
.RI /etc/automysqlbackup/automysqlbackup.conf
file
.PP
.SH AUTHOR
This manual page was written by Daniel Speichert
.nh
<daniel@speichert.pl>.
for the Debian GNU/Linux system, but can be used by others.
